spring:
  application:
    name: user_microservice
  datasource:
    url: jdbc:mysql://localhost:3306/school_management_user_db
    username: root
    password: Hrhk@4321
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  cloud:
      config:
        uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: none # Disable Hibernate's auto schema creation since Liquibase will manage the schema
    show-sql: true # Optional: Show SQL queries in logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Adjust dialect based on your database
  liquibase:
    enabled: true # Enable Liquibase
    change-log: classpath:db/master-changelog.xml # Path to your master changelog file
    contexts: development # Context to match your changelog (e.g., development, production)
    default-schema: school_management_user_db # Optional: Specify the default schema
    liquibase-schema: school_management_user_db # Optional: Schema for Liquibase's own tables (DATABASECHANGELOG, DATABASECHANGELOGLOCK)
    drop-first: false # Optional: Set to true to drop the schema before applying changes (use with caution)